# Module 2 notebook - numpy and matplotlib

In DAMI module 2 numpy and matplotlib are the central topics. In this notebook I've collected and created exercises from various Parts in order to develop my numpy and matplotlib skills.

## Part 1: DataCamp

In this part I'll demonstrate basic numpy skills and my abilty to leverage on freely available course material. I've incorporated the exercises of the [numpy module](https://goo.gl/8HTXNc) from the Datacamp course _Intro to Python for Data Science_ into this notebook.

In [ ]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

In [2]:
# height as a regular list
height = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 2, 70, 72,  72, 77, 73]

# Import numpy
import numpy as np

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 72 73 69 69 71 76 71 73 73 74  2 70 72 72 77 73]
[ 1.8796  1.8796  1.8288  1.8288  1.8542  1.7526  1.7526  1.8034  1.9304
  1.8034  1.8542  1.8542  1.8796  0.0508  1.778   1.8288  1.8288  1.9558
  1.8542]


In [3]:
# height and weight as a regular lists
height =  [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73]
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/(np_height_m)**2

# Print out bmi
print(bmi)

[ 23.11037639  27.60406069  28.48080465  28.48080465  24.80333518
  25.99036864  30.86356276  27.89402921  28.11789135  25.10462629
  24.80333518  23.7478741 ]


In [4]:
# height and weight as a regular lists
height =  [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73]
weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180]

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False False False False False False False False False False]
[]


In [7]:
np.array([True, 1, 2]) + np.array([3, 4, False])
#NumPy sums the arrays and convert true to 1 and false to 0 so that the following line is the equal solution:
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

In [ ]:
# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 50
print(np_weight[50])

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height[100:111])

In [8]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [9]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [ ]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123,0])

In [ ]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = [0.0254, 0.453592, 1]

# Print out product of np_baseball and conversion
print(np_baseball*conversion)

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height from np_baseball
np_height = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

In [ ]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

## Part 3: ipythonblocks

Indexing skills are key in numpy as well as in pandas. In this part I'll demonstrate my numpy indexing skills using [ipythonBlocks](https://goo.gl/43TKxr). I've installed the package using condas and imported it into this notebook. I'll pay specific attention to complex slicing and fancy indexing and boolean indexing. Fancy and boolean indexing are extensions for numpy and pandas and not available in regular python sequences such as lists and strings.

## Part 2: numpy exercies notebook

This part contains a selection of exercises from the [numpy 100 exercises notebook](http://bit.ly/2vN6N4F) on GitHub. I've selected some exercises that felt sufficiently challenging and that learned me something new. I've paid special attention to

- indexing (sliced, fancy, boolean/masked)
- vectorization
- broadcasting
- aggregation

These are all concepts that make numpy very efficient for vector based computing. scikit-learn algorithms heavily depend on these concepts.

In [6]:
# 1. Import the numpy package under the name np (★☆☆)
# (hint: import … as …)
import numpy as np

In [7]:
# 2. Print the numpy version and the configuration (★☆☆)
# (hint: np.__version__, np.show_config)
print(np.__version__)
print(np.show_config)

1.13.1
<function show at 0x0000026452162620>


In [8]:
# 3. Create a null vector of size 10 (★☆☆)
# (hint: np.zeros)
vec = np.array((np.zeros([10])))
print(vec)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [9]:
# 4. How to find the memory size of any array (★☆☆)
# (hint: size, itemsize)
size = vec.size
print(size)

10


In [10]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
# (hint: np.info)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [11]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
# (hint: array[4])
vec = np.array((np.zeros([10])))
vec[4] = 1
print(vec)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [12]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
# (hint: np.arange)
vec = np.array(np.arange(10,50))
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#8. Reverse a vector (first element becomes last) (★☆☆)
#(hint: array[::-1])

print(vec[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
# (hint: reshape)
vec = np.arange(0,9).reshape((3,3))
print(vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#(hint: np.nonzero)
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [16]:
#11. Create a 3x3 identity matrix (★☆☆)
#(hint: np.eye)
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#(hint: np.tile)
np_mat = np.arange(0,4)
print(np_mat)
np_tile = np.tile(np_mat,(8,2))
print(np_tile)

[0 1 2 3]
[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]


In [21]:
#22. Normalize a 5x5 random matrix 
import numpy as np
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.739745    0.91719549  0.42930096  0.98267616  0.74434431]
 [ 0.76857681  0.25045604  0.13865373  0.74296768  0.03674848]
 [ 0.01529584  0.49937498  0.18203806  0.62223261  0.87164475]
 [ 0.9788282   1.          0.36481193  0.65249844  0.        ]
 [ 0.42642613  0.9768804   0.71608799  0.60929371  0.8618708 ]]


In [18]:
#34. How to get all the dates corresponding to the month of July 2016? (★★☆)
#(hint: np.arange(dtype=datetime64['D']))
import datetime
x = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [22]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 
import numpy as np
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [19]:
#40. Create a random vector of size 10 and sort it (★★☆)
#(hint: sort)
np_randvector = np.random.randint(10,size = 10)
print(np_randvector)
np_sorted = np.sort(np_randvector)
print(np_sorted)

[8 0 9 1 7 4 5 4 5 0]
[0 0 1 4 4 5 5 7 8 9]


In [23]:
#45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#(hint: argmax)
np_vect = np.random.randint(10, size =10)
print(np_vect)
np_maxOfvect = np.argmax(np_vect)
print(np_maxOfvect)
np_vect[np_maxOfvect] = 0
print(np_vect)

[1 5 2 5 5 5 5 9 5 9]
7
[1 5 2 5 5 5 5 0 5 9]


## Part 3: Python Data Science Handbook - numpy

This part contains selected examples from the [Python Data Science Handbook](https://goo.gl/ay9Bqe). I've read through the chapter on numpy an matplotlib and here are some exercises I've extracted from them. I've adapted the code demos from the book slightly in order to better understand and learn specific features and functionality.
I end with the k-Nearest Neighbors example from the book, as this gives me some insight in the implementation of a simple machine learning algorithm.

## Parts 4: Python Data Science Handbook - matploblib

Finally I've created my own numpy dataset with randomized data. I'll use it to demonstrate my matplotlib visualization skills in the same fashion as has been done in the matplotlib chapter in the [Python Data Science Handbook](https://goo.gl/ay9Bqe).